# Generated by Django 2.1.2 on 2018-12-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20181226_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='mani',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.IntegerField()),
            ],
        ),
    ]
